name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 11
  
#    - name: Setup Android SDK Tools
#      # You may pin to the exact commit or the version.
#      # uses: android-actions/setup-android@72fdd2e74f58fb338a2743720c0847b8becf1589
#      uses: android-actions/setup-android@v2.0.2

#    - name: Build Application
#      run: ./gradlew --no-daemon build

    - name: Android Build
      # You may pin to the exact commit or the version.
      # uses: vgaidarji/android-github-actions-build@0888eff41ad409a802aa4ccd7790a91891da9056
      uses: vgaidarji/android-github-actions-build@v1.0.1
      with:
          args: "./gradlew assembleDebug"
